### ISSUE TITLE
Sur 1.X - Problèmes de config Ansible

### ISSUE THREAD

**Issue by Kevin-Bannier** [in6pio/Incipio#40]
Le répetoire doit être spécifié à chaque fois.
Ansible n'accepte pas les variables avec des tirets.

https://github.com/Kevin-Bannier/Incipio/commit/e4411707395866db65f5c8c62d1416e29e87f4e7

**Comment by theofidry** [comment]
Je vais revérifier ça, il me semble qu'il le faisait comme un grand vu qu'il ne prend ces variables comme des strings le tiret ne devrait pas poser de problème. Mais il se peut que ça ai changé.

**Comment by theofidry** [comment]
Effectivement ça à l'air d'avoir changé. L'environnement de dev jusqu'à maintenant présent seulement sur `master` va aussi être appliqué à `1.X` cf. #45.
