### ISSUE TITLE
Sur 1.X - Corrections urls Zend

### ISSUE THREAD

**Issue by Kevin-Bannier** [in6pio/Incipio#41]
Certaines urls de Zend dans composer.lock ne sont plus correctes.
Voir les diffs de composer.lock sur ce commit : https://github.com/Kevin-Bannier/Incipio/commit/52e11229a6dd755e1325d9d0688a788f90a0ccc4#diff-1da2c7edc898c70e5a79a9997c98cecc

**Comment by theofidry** [comment]
ON va voir pour le `composer.lock` avec l'issue #42.
